-
  deploy:
    RelayWithBulkStore:
      contract: ../btcBulkStoreHeaders.se
      gas: 3100000
      wait: True

# token contracts are on private testnet
# NOTE initTokenContract requires the address of the TokenFactory
# must also ensure enough gas!
# -
#   transact:
#     initTokenContract:
#       gas: 1200000
#       to: $RelayWithBulkStore
#       sig: initTokenContract:[int256]:int256
#       data:
#         - 0x55a285c6f02fcb7ba51c44d5a019153d8e39390e
#       retry: 60
#       wait: True

# parent block is Bitcoin Livenet
-
  transact:
    SetInitialParent:
      gas: 150000
      to: $RelayWithBulkStore
      sig: setInitialParent:[int256,int256,int256]:int256
      data:
        - 0x00000000000000000cd20cf178b714cae163a9541340526237a1a161592ebf68
        - 378679
        - 1
      retry: 60
      wait: True
